### ISSUE TITLE
In the config, the slashes in the routes_namespace value breaks route:scan on a Mac

### ISSUE THREAD

**Issue by wpjmurray** [ProAI/lumen-route-annotations#3]
In config/annotations.php

`'routes_namespace' => 'App\Http\Controllers'`

This does not work on a Mac when using `php artisan route:scan` because this value is converted to a portion of a file path where slashes should be forward slashes. Here is the error returned by route:scan

`[InvalidArgumentException]`
`The "/Users/me/Project/app/Http\Controllers" directory does not exist.`

Note the inconsistent slashes in the reported path. Changing `routes_namespaces` to `'App/Http/Controllers'` works correctly.

Expected behavior: When namespacing in PHP using back slashes is required so we expect that the value of routes_namespace should use back slashes, so the default value is correct and should work. However, when converting this namespace to a path in ProAI\Annotations\Metadata\ClassFinder::getClassesFromNamespace() these slashes should be converted to the correct file path format expected by the platform it is running on.

**Comment by markusjwetzel** [comment]
Thank you! I fixed it. The behavior should now fit to the expected behavior, that you have described.
